[platformio]
default_envs = i2c

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MLX90393@^2.0.3
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
board_build.extra_flags =
    -DBOARD_HAS_PSRAM
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DSENSOR_ROLE_ID=2

[env:i2c]
build_flags =
    ${env.build_flags}
    -DMLX_TRANSPORT_SPI=0

[env:spi]
build_flags =
    ${env.build_flags}
    -DMLX_TRANSPORT_SPI=1
